name: second workflow

on:
  push:
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: welcome
        run: echo "welcome to the devops"

  bye-job:
    runs-on: ubuntu-latest

    steps:
      - name: bye
        run: echo "bye bye"