name: "first workflow"
on: 
  push:
  pull_request:


jobs: 
     first-job:
       runs-on: ubuntu-latest
       steps:
           - name: checkout
             uses: actions/checkout@v4
             with: 
               node-verison: 24
               chache: npm

           - name: "setup node js in VM"
             uses: actions/setup-node@v4


           - name: install dependency
             run: npm ci

           - name: run eslint in app
             run: npm run lint

           - name: make react build
             run: npm run build
