name: "first workflow"
on: 
  push:
  pull_request:


jobs: 
     first-job:
       runs-on: ubuntu-latest
       steps:
           - name: checkout
             uses: actions/checkout@v4
             with: 
               node-verison: 24
               chache: npm
           - name: install dependency
             run: npm ci

           - name: make react build
             run: npm run build
