name: Jobs Test
on:
  workflow_run:
    workflows: [First Workflow]
    types:
      - completed
jobs:
    validate-html:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: Ubuntu-latest
       
        steps:
        - name: get-repo-code
          uses: actions/checkout@v4

        - name: validate html file
          run: test -f index.html

    validate-js:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: Ubuntu-latest

        steps:
        - name: get-repo-code
          uses: actions/checkout@v4

        - name: validate js file
          run: test -f script.js

    validate-code:
        needs: [validate-html, validate-js]
        runs-on: Ubuntu-latest

        steps:
        - name: get-repo-code
          uses: actions/checkout@v4

        - name: validate js code
          run: node --check script.js
        
        - name: validate html code
          run: npx htmlhint index.html
            