name: validate files
on: push
jobs: 
    validate-file:
      runs-on: ubuntu-latest
     
      steps: 
      - name: get-repo-code
        uses: actions/checkout
      
      - name: validate html file
        uses: test -f index.html

      - name: validate js file
        uses: test -f script.js